apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c6jqo8vtf-nodejs 
  janus-idp.io/tekton: c6jqo8vtf-nodejs
  backstage.io/kubernetes-id: c6jqo8vtf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6jqo8vtf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml