apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c6jqo8vtf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c6jqo8vtf-nodejs 
  name: c6jqo8vtf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: c6jqo8vtf-nodejs 
